export const TokenType = {
  Keyword: "keyword",
  Identifier: "identifier",
  Number: "number",
  String: "string",
  Boolean: "boolean",
  Null: "null",
  Operator: "operator",
  LParen: "lparen",
  RParen: "rparen",
  LBracket: "lbracket",
  RBracket: "rbracket",
  LBrace: "lbrace",
  RBrace: "rbrace",
  Comma: "comma",
  Range: "range",
  Slice: "slice",
  Spread: "spread",
  Backtick: "backtick",
  StringFragment: "string_fragment",
  InterpolationStart: "interpolation_start",
  InterpolationEnd: "interpolation_end",
  Colon: "colon",
  At: "at",
};

export const END_KEYWORDS = [
  'end', 'else'
];

export const KEYWORDS = [
  "set",
  "let",
  "const",
  "global",
  "destructure",
  "from",
  "if",
  "guard",
  "then",
  "when",
  "while",
  "function",
  "fn",
  "call",
  "show",
  "return",
  "try",
  "catch",
  "throw",
  "for",
  "in",
  "match",
  "case",
  "default",
  "break",
  "continue",
  "loop",
  "true",
  "false",
  "null",
  "import",
  "as",
  "export",
  "not",
  "and",
  "or",
  ...END_KEYWORDS
];

export const Punctuators = {
  Semicolon: ";",
  Comma: ",",
  Dot: ".",
  Question: "?",
  Spread: "...",
  Colon: ":",
  LParen: "(",
  RParen: ")",
  LBracket: "[",
  RBracket: "]",
  LBrace: "{",
  RBrace: "}",
  Pipe: "|",
  Ampersand: "&",
};

export const Keywords = {
  set: TokenType.Keyword,
  let: TokenType.Keyword,
  const: TokenType.Keyword,
  global: TokenType.Keyword,
  if: TokenType.If,
  while: TokenType.Keyword,
  function: TokenType.Keyword,
  call: TokenType.Keyword,
  show: TokenType.Keyword,
  return: TokenType.Keyword,
  try: TokenType.Keyword,
  catch: TokenType.Keyword,
  throw: TokenType.Keyword,
  for: TokenType.Keyword,
  in: TokenType.Keyword,
  match: TokenType.Keyword,
  case: TokenType.Keyword,
  default: TokenType.Keyword,
  break: TokenType.Keyword,
  continue: TokenType.Keyword,
  loop: TokenType.Keyword,
  true: TokenType.True,
  false: TokenType.False,
  null: TokenType.Null,
  import: TokenType.Import,
  export: TokenType.Export,
};

export const Operators = {
  "+": TokenType.Plus,
  "-": TokenType.Minus,
  "=": TokenType.Equal,
  "==": TokenType.EqualEqual,
  "===": TokenType.EqualEqualEqual,
  "!=": TokenType.BangEqual,
  "!==": TokenType.BangEqualEqual,
  ">": TokenType.Greater,
  "<": TokenType.Less,
  ">=": TokenType.GreaterEqual,
  "<=": TokenType.LessEqual,
  "&&": TokenType.And,
  "||": TokenType.Or,
};
